"""
File and folder deleting tools
"""
from os import rmdir, remove

def removechain(src: dict):
	"""
	Remove files and folders created by copy paste(-ing)
	"""
	for i in src["file"]:
		remove(i)
	for i in src["dir"]:
		rmdir(i)

def removefixed(folder: str):
	"""
	Remove known unchanged files
	"""
	remove(f'./tools/backtools/zip/{folder}-dumpfile.txt')
	remove(f'./tools/backtools/zip/{folder}-dumpdir.txt')

def removeall(src: dict, folder: str) -> None:
	"""
	Remove all files and folders generated by "dump(ing)" and copy paste(-ing)
	"""
	removechain(src)
	removefixed(folder)
